
// interface Post {
//   id: number;
//   title: string;
//   content: string;
//   author: string;
//   date: string,
//   category: string;
// }
// export default async function Page() {
//   let data = await fetch('https://api.vercel.app/blog')
//   let posts : Post[] = await data.json()
//   console.log(posts)
//   return (
//     <ul>
//       {posts.map((post) => (
//         <li key={post.id}>{post.title}</li>
//       ))}
//       about sas
//     </ul>
//   )
// }

import { Metadata } from "next";
// import { useEffect, useState } from "react";
// import useSWR from 'swr'

// interface Post {
//   id: number;
//   title: string;
//   content: string;
//   author: string;
//   date: string;
//   category: string;
// }

export const metadata: Metadata = {
  title: "About Us",
  description: " About Us Generated by create next app 15",
  applicationName: 'Next.js 15 data fetching and seo',
  keywords: "Next.js, React, TypeScript",
  authors: [{
    name: 'Rishi Anand',
  }],
  openGraph: {
    type: 'website',
    url: 'https://nextjs.org',
    title: 'Create Next App',
    description: 'Generated by create next app',
    images: [
      {
        url: 'https://nextjs.org/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Og Image Alt',
      },
    ],
  },
  twitter: {
    site: 'Rishi Anand',
    creator: 'Rishi Anand',
    description: ' About Generated by Rishi Anand',
    title: 'About Rishi Anand',
  }
};

// {
//   businessUnitId: process.env.NEXT_PUBLIC_BUSINESS_UNITID,
// },
// {
//   headers: {
//     Authorization: `${token}`,
//   },
// }

interface AboutUsResponse {
  aboutUs: string;
  activeFlag: boolean;
  businessUnitId: string;
  creationDate: string;
  deleteFlag: boolean;
  heading: string;
  id: string;
  modifiedDate: string;
  _id: string;
}

export default async function Page() {
  const data = await fetch(`${process?.env?.NEXT_PUBLIC_API_BASE_URL}/about-us/filter`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      clientid : process?.env?.NEXT_PUBLIC_CLIENT_ID as string,
      secret : process?.env?.NEXT_PUBLIC_SECRET as string,
      Authorization : 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGIxODMwNDYxYmRkZTQ4Y2UxMzg5MGMiLCJhcHBUeXBlIjoiNjVkYzI3N2M5ODYzNjFlYzgwZDMwMDZlIiwicm9sZUlkIjoiNjMyMDc4OTVjZmZkN2MyMWViZTdjOGY2Iiwic2Vzc2lvbklkIjoiYWxwaGFudW1lcmljIiwiaWF0IjoxNzMzMDM0MjkyLCJleHAiOjE3MzMyMDcwOTJ9.b1oUz9eghT0GNYQcXYE5CRSNGj37RJ9sRhfVJQhDa0s'
    },
    body: JSON.stringify({ businessUnitId: "661e24a0d3d7d8a112f2940f" }),
  })
  const aboutUsRes = (await data.json()).data
  return (
    <ul>
      {aboutUsRes?.map((about : AboutUsResponse) => (
        <div key={about.id}>
          <h3>{about?.heading}</h3>
        <li dangerouslySetInnerHTML={{ __html: about?.aboutUs }} />
        </div>
      ))}
      about sas
    </ul>
  )
}