// import Image from "next/image";
import styles from "./page.module.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nextjs 15 Create Next App",
  description: "Generated by create next app 15",
  applicationName : 'Next.js 15 data fetching and seo',
  keywords: "Next.js, React, TypeScript",
  openGraph : {
    type: 'website',
    url: 'https://nextjs.org',
    title: 'Create Next App',
    description: 'Generated by create next app',
    images: [
      {
        url: 'https://nextjs.org/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Og Image Alt',
      },
    ],
  },
  twitter : {
    site : 'Rishi Anand',
    creator : 'Rishi Anand',
    description : 'Generated by Rishi Anand',
    title : 'Rishi Anand',
  }
};
export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
          <h3>Welcome to Next js 15</h3>
        </main>
    </div>
  );
}
