
// interface Post {
//   id: number;
//   title: string;
//   content: string;
//   author: string;
//   date: string,
//   category: string;
// }
// export default async function Page() {
//   let data = await fetch('https://api.vercel.app/blog')
//   let posts : Post[] = await data.json()
//   console.log(posts)
//   return (
//     <ul>
//       {posts.map((post) => (
//         <li key={post.id}>{post.title}</li>
//       ))}
//       about sas
//     </ul>
//   )
// }


// import { Metadata } from "next";
import { GenerateToken } from "../service/token_generator";
// import { useEffect, useState } from "react";
// import useSWR from 'swr'

// interface Post {
//   id: number;
//   title: string;
//   content: string;
//   author: string;
//   date: string;
//   category: string;
// }

// export const metadata: Metadata = {
//   title: "About Us",
//   description: " About Us Generated by create next app 15",
//   applicationName: 'Next.js 15 data fetching and seo',
//   keywords: "Next.js, React, TypeScript",
//   authors: [{
//     name: 'Rishi Anand',
//   }],
//   openGraph: {
//     type: 'website',
//     url: 'https://nextjs.org',
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//     images: [
//       {
//         url: 'https://nextjs.org/og-image.png',
//         width: 1200,
//         height: 630,
//         alt: 'Og Image Alt',
//       },
//     ],
//   },
//   twitter: {
//     site: 'Rishi Anand',
//     creator: 'Rishi Anand',
//     description: ' About Generated by Rishi Anand',
//     title: 'About Rishi Anand',
//   }
// };

// {
//   businessUnitId: process.env.NEXT_PUBLIC_BUSINESS_UNITID,
// },
// {
//   headers: {
//     Authorization: `${token}`,
//   },
// }
interface AlbumResponse {
  userId: number;
  id: number;
  title: string;
}

export default async function Page() {
  const tokenResponse = await GenerateToken();
  const token = tokenResponse.access_token; 
  console.log(token, "token")
  const data = await fetch(`https://jsonplaceholder.typicode.com/albums`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
  })
  const albumRes = await data.json()
  return (
    <ul>
      {albumRes?.map((album: AlbumResponse) => (
        <div key={album.id}>
          <h3>UserId : {album?.userId}</h3>
          <li>Title : {album?.title}</li>
        </div>
      ))}
    </ul>
  )
}
